Option to run specific migration(s), refs #13368
artefactual/atom pull request #1138
Opened 2020-06-27 20:16 UTC by mcantelon

Added option, to the tools:upgrade-sql task, to run specific migrations
rather than a full upgrade.

2020-07-15 17:49 UTC, djjuhasz requested changes
Looks pretty good @mcantelon, I just have a few suggestions. :)

2020-07-15 17:49 UTC, djjuhasz commented on lib/task/migrate/arUpgradeSqlTask.class.php
> +      new sfCommandOption('number', 'n', sfCommandOption::PARAMETER_OPTIONAL, 'Run only specific migration number(s)', null),
I think it would be helpful to indicate in the help text that multiple numbers should be comma-separated.

2020-07-15 17:49 UTC, djjuhasz commented on lib/task/migrate/arUpgradeSqlTask.class.php
> +      foreach (explode(',', $options['number']) as $number)
I think it would be better to factor the `$number` option code into a separate method to aid readability.

2020-07-15 17:49 UTC, djjuhasz commented on lib/task/migrate/arUpgradeSqlTask.class.php
> +          if (true !== $class->up($this->configuration))
I think this should use a `try ... catch` block like the main execution path.

2020-07-15 17:49 UTC, djjuhasz commented on lib/task/migrate/arUpgradeSqlTask.class.php
> +      foreach (sfFinder::type('file')
I think it would be better to factor this (main) execution branch into a separate method to aid code readability.

2020-07-23 21:18 UTC, mcantelon commented
@djjuhasz Thanks for the review... got sidetracked, but have updated the branch!

2020-08-13 23:49 UTC, djjuhasz commented on lib/task/migrate/arUpgradeSqlTask.class.php
> +          if (true !== $class->up($this->configuration)) throw new sfException('Failed to apply upgrade '.get_class($class));
I think this is a good opportunity to make this "if () throw ..." statement (and the one below) follow our coding standard and add the parantheses and newlines, e.g. 

```
if (true !== $class->up($this->configuration)) 
{
  throw new sfException('Failed to apply upgrade '.get_class($class));
}
```

2020-08-13 23:50 UTC, djjuhasz approved these changes
Looks good @mcantelon. I just had one request to bring the legacy code in line with our coding standard. 👍

2020-08-14 05:17 UTC, merged