Get treeview data from Elasticsearch, refs #13423
artefactual/atom pull request #1205
Opened 2020-10-16 16:49 UTC by djjuhasz

- Refactor full width treeview code
- Get information object data for the treeview from Elasticsearch 
   because it is already normalized, runs faster, and uses less memory
- Add information_object.lft column data to Elasticsearch index to
  allow sorting search results on the column
- Wrap long lines

2020-10-16 22:06 UTC, jraddaoui commented
Hi @djjuhasz,

I only read the PR description so I'm not sure if you took in consideration the recent changes from the CSV import, where the nested set is not updated until the end of the process (without updating those values in ES):

https://projects.artefactual.com/issues/13356
https://projects.artefactual.com/issues/13354

The idea was to use similar changes in other import process to improve their performance, with a bigger goal to remove the nested set altogether:

https://projects.artefactual.com/issues/13385
https://projects.artefactual.com/issues/13240

I can see the benefits of using ES for this matter and we still need to evaluate the pros of fully removing it (better hierarchy updates) versus the cons (worst hierarchy reads), but I think this change goes in a different direction and that we should think a bit more about how we manage hierarchical data and how it's passed to ES so we can use it in places like the tree-view for reads without major impact in process like imports for updates.

Please, let me know your thoughts and sorry for not being involved in this sooner, I didn't know it was coming.

2020-10-16 22:14 UTC, djjuhasz commented
@jraddaoui I didn't switch to Elasticsearch because of the nested set queries - I did it because getting the data from MySQL required six joins and a one-to-many query on the `event` table for each row returned and it caused PHP to eat up a ton of memory (over 4 GB).    I started trying to optimize the query by using a recursive CTE to traverse the hierarchy, but pretty quickly came to the conclusion that it wasn't going to significantly improve the query performance.

All of the data required for a full width treeview node is in a single ES information object document, so it's naturally much faster and more memory efficient to get the data from ES.

2020-10-16 22:56 UTC, jraddaoui commented
@djjuhasz, I see that, I think we are using a recursive process with lazy load, not nested set queries. But I can see the benefits of using ES, as I said.

My only concern is that we can't trust the `lft` values to sort siblings after the latest changes from the CSV import. In fact, we can't even trust them in the DB (see [#13414](https://projects.artefactual.com/issues/13414)), but in ES they will be empty unless the index is rebuilt after the import.

I'm not saying this changes are not good or that they won't benefit the tree-view performance, just that we may move in a different direction to manage hierarchical data, which will require to modify this implementation again (as it would with the current one). I'd love to see all happening together but I guess that won't be the case, since removing the nested set entirely is not a minor task and you already have these changes almost ready. And after all, we may only need to change the sort field for the tree-view as it's already a recursive implementation. Nevertheless, until them, I think we should consider the issues mentioned with the `lft` values.

2020-10-16 23:07 UTC, djjuhasz commented
Ah, thanks for explaining further @jraddaoui.

Is there an alternative column I can use to sort siblings other than `lft` that will match the previous treeview sorting (which was on the `lft` value)?  I understand that the ES `lft` value might be out of date with the MySQL `lft` value, but I worry changing the treeview sort will annoy AtoM users that have sorted their descriptions in a meaningful way.

2020-10-17 00:18 UTC, jraddaoui commented
Yeah, there is no alternative so far, not until we move to that "order" column if we decide to do so at some point. And it's hard to see how can we trust the `lft` value without going back to the performance/deadlock issues.

As a workaround, maybe we could use a placeholder left value in the import process, auto-incrementing for siblings without updating the nested set in other rows from the IO table. That value will go to ES until the nested set update changes those values in the DB at the end of the import, and it could act as an order column because the process is already recursive. Just an initial idea as there may be a lot of things to consider, for example existing siblings to start the placeholder counter or how rebuilding the index will probably change those values after the nested set update; although, I think it could help with #13414 too, so maybe it's worth a try.

2020-10-19 22:06 UTC, djjuhasz commented
@jraddaoui hmm, I've been wrestling with how to proceed on this Pull Request all morning.  🙁 

To summarize my understanding of the problem:

1. [Issue 13414](https://projects.artefactual.com/issues/13414) CSV import no longer updates the `lft` column in the database during the import (to fix [issue 13354](https://projects.artefactual.com/issues/13354)), so the `lft` values for siblings created by an import do not match the ordering in the CSV import file .
2. Because the `lft` values in the database are not populated until the end of the import process, if the `--index` import option is used the Elasticsearch documents created during the import will have an empty `lft` value
3. Running a full `search:populate` after an import will populate the Elasticsearch `lft` values, but because of #1 the sibling order will still be random
4. Because of #1 and #2, the database `lft` values for newly imported records will be random, but the Elasticsearch `lft` values will be random *and* may be empty

Is that your understanding as well?

I think fixing issue 13414 (random sibling ordering) is important for AtoM, but it's too big of a change to include in this Pull Request.   The problem of the `lft` value in the Elasticsearch index being empty in some cases is not great, but there is a work around (running `search:populate`).  Since we can't guarantee the sibling order for the treeview in any case without fixing issue 13414 I think using the ES `lft` value for the treeview sort is an acceptable trade-off for better memory performance and treeview load speed.  I also don't think sorting by ES `lft` now makes it significantly harder to fix Issue 13414 in the future.

My proposal is to ignore the ES `lft` sort problem for this Pull Request and address it with the fix for Issue 13414.  I know it's not an ideal solution, but I think it's the best compromise for now.

2020-10-20 14:40 UTC, jraddaoui commented
Hi @djjuhasz,

> Is that your understanding as well?

Yes, exactly. It's worth noting that CSV GUI imports behave that way by default.

> I think fixing issue 13414 (random sibling ordering) is important for AtoM, but it's too big of a change to include in this Pull Request. The problem of the lft value in the Elasticsearch index being empty in some cases is not great, but there is a work around (running search:populate). Since we can't guarantee the sibling order for the treeview in any case without fixing issue 13414 I think using the ES lft value for the treeview sort is an acceptable trade-off for better memory performance and treeview load speed. I also don't think sorting by ES lft now makes it significantly harder to fix Issue 13414 in the future.

I agree.

> My proposal is to ignore the ES lft sort problem for this Pull Request and address it with the fix for Issue 13414. I know it's not an ideal solution, but I think it's the best compromise for now.

Sounds good.

I see @mcantelon is assigned for review and I'm feeling a bit off today, so I'll let him deal with the actual code.

Thanks David.

2020-10-20 17:01 UTC, mcantelon requested changes
Great improvement/refctoring... cleans things up a lot!

The file `apps/qubit/modules/browse/actions/hierarchyDataAction.class.php` seems like it needs to be updated as enabling "Show browse hierarchy page" in treeview settings and visiting  browse/hierarchy results in a 500 error as the function "getNodeOrChildrenNodes" has been removed.

Other thn that I only found one issue with a comment. Nicely done!

2020-10-20 17:01 UTC, mcantelon commented on apps/qubit/modules/default/actions/fullTreeViewAction.class.php
> +   * @param int $informationObjectId information object id
The function doesn't have this parameter.

2020-10-21 00:44 UTC, djjuhasz commented on apps/qubit/modules/default/actions/fullTreeViewAction.class.php
> +   * @param int $informationObjectId information object id
Oops, yeah that comment is totally unrelated to that method 🤦

2020-10-21 00:44 UTC, djjuhasz commented on apps/qubit/modules/default/actions/fullTreeViewAction.class.php
> +   * @param int $informationObjectId information object id
Copy & paste error.... 😛

2020-10-21 00:46 UTC, djjuhasz commented
Thanks @mcantelon! Good catch on the browse hierarchy page using the old `getNodeOrChildrenNodes()` method. 😅 

I've added new commits with the fixes so you can review them easily - I'll squash them into the main commit before I merge.

2020-10-23 17:20 UTC, mcantelon approved these changes
Looks good to me! Really nice refactoring! 👍

2020-10-23 21:35 UTC, merged