Add job data support to expiry task, refs #13440
artefactual/atom pull request #1222
Opened 2020-11-23 22:18 UTC by mcantelon

* Fixes bug where clipboard maximum age setting wasn't getting read
* Adds the ability ro expire job data and related temporary user
  download files
* Adds the ability to expire multiple types of data in one run
* Code refactoring/cleanup

2020-11-24 20:02 UTC, djjuhasz requested changes
Looks good overall @mcantelon, I just had a few questions and comments.

2020-11-24 20:02 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +        if (!ctype_digit($maxAge))
I think `ctype_digit()` will return false here if `$maxAge` is an integer between -128 and 255 (See https://www.php.net/manual/en/function.ctype-digit.php#example-5540).  It's not a problem here if `sfConfig::get($typeSpec['age_setting_name'])` always returns a string value, but I'm not sure if that is the case. 🤔

2020-11-24 20:02 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +      $maxAge = sfConfig::get($typeSpec['age_setting_name']);
I think this will emit a warning if the `$typeSpec['age_setting_name']` key is not set for `$typeSpec`.  Instead of putting `isset($typeSpec['age_setting_name'])` in the previous line, I think it would be better to do something like:

`$maxAge = isset($typeSpec['age_setting_name']) ? sfConfig::get($typeSpec['age_setting_name']) : null;`

The following conditional should still evaluate to false if $maxAge is null.

2020-11-24 20:02 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +      // Set older than option if not set and a non-zero maximum age is set for data type
Opinion: I think it would be better to move the logic for determining `$options['older-than']` when it's not explicitly set to it's own method to make it easier to track the main execution path.

2020-11-24 20:02 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +        $this->logSection(
Nice 👍

2020-11-24 20:02 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +      // Finding aids won't be deleted because the job doesn't store the path to them
_Not_ deleting finding aids is the desired behavior, right?  I think it would be helpful to make this explicit in the comment. :)

2020-11-25 04:32 UTC, mcantelon commented on lib/task/tools/expireDataTask.class.php
> +        if (!ctype_digit($maxAge))
Yikes! Fixed.

2020-11-25 04:33 UTC, mcantelon commented
Thanks @djjuhasz... I've committed an update for the PR!

2020-11-25 04:48 UTC, mcantelon commented on lib/task/tools/expireDataTask.class.php
> +      // Set older than option if not set and a non-zero maximum age is set for data type
Good idea.

2020-11-25 18:00 UTC, djjuhasz requested changes
Looking good @mcantelon, I just suggested a couple of minor tweaks.

2020-11-25 18:00 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +                         && isset($typeSpec['age_setting_name']);
You can drop the `&& isset($typeSpec['age_setting_name']);` here, as it is tested below. :)

2020-11-25 18:00 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +        sfConfig::get($typeSpec['age_setting_name'])
I'd use `$maxAge` instead of `sfConfig::get($typeSpec['age_setting_name'])` here, as it's shorter and already assigned.

2020-11-25 18:00 UTC, djjuhasz commented on lib/task/tools/expireDataTask.class.php
> +      // Jobs generate finding aids, which we *don't* want to delete... finding
Nice! 👍

2020-11-26 00:01 UTC, mcantelon commented
Thanks again @djjuhasz... the max age check is now considerably saner... I've updated the PR! ;)

2020-11-26 00:32 UTC, djjuhasz approved these changes
Looks good @mcantelon! :shipit:

2020-11-26 02:48 UTC, merged