Fix incorrect field name
artefactual/atom pull request #1562
Opened 2023-02-03 22:38 UTC by sunnywd

I've corrected the field name for 'Digital object available' field on the Authority search page.
'hasDigitalObject' looks to be the correct field name, instead of 'relatedType'.

2023-02-07 20:33 UTC, mcantelon commented
Hi Sunny! Thanks for the contribution... nice fix!

Your PR looks good... just one minor change needed. Could you change the commit message to the following?

```
Fix B5 template actor search field, refs #13645
    
Fixes a misnamed field in the Dominion B5 theme's actor search
    template.
```
Thanks!

2023-02-07 20:34 UTC, mcantelon requested changes
Looks good! Just one small change to the commit message needed! Thanks!

2023-02-08 00:13 UTC, sunnywd commented
I've updated the commit message as advised. Thanks!

2023-02-09 04:03 UTC, mcantelon commented
Excellent... thanks Sunny!

2023-02-09 04:05 UTC, mcantelon approved these changes
Looks good! Thanks for the fix!

2023-02-09 04:06 UTC, merged

2023-02-15 18:52 UTC, mcantelon commented
Hi Sunny! One thing I forget was to get you to sign and scan a Contributor Licence Agreement. Would you be able to do that? It's a one-time thing so any subsequent pull requests you submit will be covered as well.

https://wiki.accesstomemory.org/images/9/9d/Accesstomemory-contributor-agreement-2014.pdf

2023-02-15 19:24 UTC, sunnywd commented
Hi Mike. I already submitted one on May 9th, 2022 to Dan, cc'ing agreement@artefactual.com.

2023-02-15 21:33 UTC, mcantelon commented
Oops... sorry about the mixup, Sunny! Cheers!