Add CLI data integrity repair tool
artefactual/atom pull request #1725
Opened 2023-12-06 19:14 UTC by anvit

Add a CLI tool for performing data integrity checks and repairing or deleting broken records.

2024-03-11 18:32 UTC, jraddaoui requested changes
Thank you for adapting this @anvit and sorry for the delay on the review.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +            $this->log(sprintf("  - %s: %d\n", $class, $fixed));
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        $this->log("Checking descriptions integrity:\n");
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        $this->log(sprintf("  - Descriptions without object row: %d\n", QubitPdo::fetchColumn($sql)));
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        $this->log(sprintf("  - Descriptions without parent id: %d\n", QubitPdo::fetchColumn($sql)));
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        $this->log(sprintf("  - Descriptions without parent: %d\n", QubitPdo::fetchColumn($sql)));
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        $this->log(sprintf("  - Descriptions without publication status: %d\n", QubitPdo::fetchColumn($sql)));
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        $this->log(sprintf("  - Affected descriptions: %d\n", count($affectedIos)));
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +            $this->log("All descriptions seem to be okay.\n");
Use `$this->logSection()`.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        );
Indentation is wrong, it would fit in one line too.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +      }
Indentation is wrong here too, how is this not found by the syntax checker?

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +- Add missing object rows for all resources extending QubitObject
Use `Adds` for consistency.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +- Checks descriptions with missing data and provides options for attempting to generate a list, fix them, or delete them
Include `Re-builds the nested sets` or something like that in this list.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +          $this->report($filename, $affectedIosById, $affectedIosAndDescendantIds);
Report happens in all cases, you could remove the breaks and make all cases fall down to the default, not needing to call the report generation on each case. You could also move the report generation before the switch and remove the default case.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        );
Indentation/one-line.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        );
Indentation/one-line.

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +            new sfCommandArgument('filename', sfCommandArgument::OPTIONAL, 'A name for the generated CSV report file', 'affected-records.csv'),
A filepath instead of a name and clarify it requires the `.csv` extension (so we could remove the check below).

2024-03-11 18:32 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +        }
Maybe clarifying a CSV path is required, this is no lo longer needed.

2024-03-11 18:35 UTC, jraddaoui commented
I don't know what are the plans for documentation, but we should explain somewhere the meaning of the CSV and the issues that can be found there.

2024-03-19 17:01 UTC, anvit commented
@jraddaoui Just addressed the feedback! Not sure why PHP-CS fixer didn't catch indentation issues because it seems to be catching other things in the file just fine, but those should be fixed now

2024-03-19 17:40 UTC, jraddaoui approved these changes
Thanks @anvit!

2024-03-19 17:40 UTC, jraddaoui commented on lib/task/tools/dataIntegrityRepairTask.class.php
> +    }
I think you can remove this function now.

2024-03-19 17:58 UTC, melaniekung approved these changes
Looks good to me! Thanks Anvit!

2024-03-19 20:55 UTC, merged