Fix memprof dockerfile typo (#1739)
artefactual/atom pull request #1740
Opened 2024-01-26 21:59 UTC by phalene-bytes

Docker images should now build successfully

2024-02-02 16:55 UTC, melaniekung requested changes
hi eleanor, this fix looks good to me! but before we merge, can you provide a little more details on this fix in the commit message? was it really a typo or a dependency req for an image we're using in docker? also, a little background on what this pkg is used for, that would also be great. thank you!

2024-02-06 20:21 UTC, phalene-bytes commented
@melaniekung Mmm what do you think I should put?  After the fix, the rest of the Dockerfile commands are able to run (like building the B2 & B5 themes). Should I put:

Fix: Typo in Dockerfile (`php8-pecl-memprof` should be `php81-pecl-memprof`)
This dependency is a memory profiler for PHP, used to identify memory leaks in PHP scripts. The typo caused issues in subsequent Dockerfile commands. 

For more information, see: https://github.com/artefactual/atom/pull/1452

2024-02-06 20:59 UTC, melaniekung commented
i couldn't confirm if it was a typo or if the difference is due to support for php 8 vs php 8.1 since docker used to build fine. if my assumption is correct, then i'd say something like "Update pecl-memprof dependency, a memory profiler for PHP used to identify memory leaks in PHP scripts". otherwise "Fix typo for pecl-memprof dependency, a memory profiler for PHP used to identify memory leaks in PHP scripts" will do.

2024-02-08 21:25 UTC, melaniekung approved these changes

2024-02-08 21:34 UTC, merged