Fix clipboard for empty browser cache (#1783)
artefactual/atom pull request #1784
Opened 2024-03-26 18:18 UTC by anvit

Set browser local storage values for clipboard if their corresponding variables are null on load, which happens if the browser storage is cleared.

2024-03-26 20:16 UTC, jraddaoui requested changes
Thanks @anvit!

2024-03-26 20:16 UTC, jraddaoui commented on js/clipboard.js
>      }
I'd change the following block:

```js
    this.items = JSON.parse(this.storage.getItem('clipboard'));
    this.exportTokens = JSON.parse(this.storage.getItem('exportTokens'));

    if (!this.items)
    {
      this.items = this.initialItems;
      this.storage.setItem('clipboard', JSON.stringify(this.initialItems));
    }

    if (!this.exportTokens)
    {
      this.exportTokens = [];
      this.storage.setItem('exportTokens', JSON.stringify([]));
    }
```

To this:

```js
    this.items = JSON.parse(this.storage.getItem('clipboard')) || this.initialItems;
    this.exportTokens = JSON.parse(this.storage.getItem('exportTokens')) || [];
```

I know that's just an optimization that won't fix the issue, but then you can do the same inside the toggle functions:

```js
    this.items = JSON.parse(this.storage.getItem('clipboard')) || this.initialItems;
```

I think that's better than writing the default/empty values into localstorage.

2024-03-26 23:07 UTC, anvit commented on js/clipboard.js
>      }
@jraddaoui Makes sense, this makes the code much cleaner! I've updated it, thanks!

2024-03-27 03:28 UTC, jraddaoui approved these changes
Thanks!

2024-03-27 03:28 UTC, jraddaoui commented on plugins/arDominionB5Plugin/js/clipboard.js
> +      this.initialItems = {
Nitpick: it could go in one line now.

2024-03-27 03:29 UTC, jraddaoui commented
Make sure you make Prettier happy ;)

2024-03-27 20:58 UTC, merged