Dev/issue 10232 do geolocation
artefactual/atom pull request #438
Opened 2016-09-20 04:55 UTC by mcantelon

Added ability to specify latitude/longitude of digital object and show resulting map on description pages:
* Add ability for admins to toggle display of digital object map on default page elements page
* Add ability to specify latitude/longitude when editing digital object metadata

AtoM tweaks/fixes related to feature:
* Change Google Maps API setting from config file var to DB setting
* Fix issue with use of get_partial instead of get_component when displaying digital object metadata
* Darken links within info alerts

2016-09-22 17:56 UTC, sevein commented
Ready for review or still work in progress, @mcantelon?

2016-09-23 18:29 UTC, mcantelon commented
I talked with Sara and realized that I'd missed one feature... will get PR review ready today.

2016-09-23 23:48 UTC, mcantelon commented
Alright, this one's ready to roll.

2016-09-27 19:38 UTC, sevein requested changes
Pretty good, only a few changes suggested!

2016-09-27 19:38 UTC, sevein commented on apps/qubit/modules/settings/templates/pageElementsSuccess.php
> +                <div id="notice-alerts" class="alert alert-info">
Should we use our standard `<div class="description">...</div>` instead? See: https://imgur.com/a/5hH4r.

2016-09-27 19:38 UTC, sevein commented on apps/qubit/modules/settings/actions/securityAction.class.php
> +    $googleMapsApiKey = QubitSetting::getByName('google_maps_api_key');
I'm not sure if the security page is the best place for the Google Maps JavaScript API key. It's not even a secret, is it? I'd personally prefer to see it (by order of preference): 1) in the same place where you enable the map element (under default page elements, see: https://imgur.com/a/M0tqq), or 2) in a new settings section ("Third-party integrations"?), or 3) under global, which is kind of a sink of all kind of settings.

2016-09-27 19:38 UTC, sevein commented on plugins/sfIsdiahPlugin/modules/sfIsdiahPlugin/templates/indexSuccess.php
> +  <div id="front-map" class="simple-map" data-key="<?php echo $keyProperty->value ?>" data-latitude="<?php echo $latitude ?>" data-longitude="<?php echo $longitude ?>"></div>
This is correct but is it necessary?  `lib/filter/QubitSettingsFilter.class.php` loads sfConfig with the settings in `QubitSetting`. In theory `sfConfig::get('app_google_maps_api_key')` should still return the value of `google_maps_api_key` even after the migration to `QubitSetting`. Not 100% sure but give it a shot? Take a look at the filter too if you can!

2016-09-27 19:38 UTC, sevein commented on apps/qubit/modules/digitalobject/actions/metadataComponent.class.php
> +    $keyProperty = QubitSetting::getByName('google_maps_api_key');
If you use the sfConfig store instead you'll save a hit to the database,  settings are populated in `sfConfig` from our cache backend.

2016-09-27 19:38 UTC, sevein commented on plugins/sfIsadPlugin/modules/sfIsadPlugin/templates/indexSuccess.php
> +    <?php echo get_component('digitalobject', 'metadata', array('resource' => $resource->digitalObjects[0], 'infoObj' => $resource)) ?>
Good catch!

2016-09-27 19:39 UTC, sevein commented
What's the public ticket? #10232 is private, we should name branches after the public ticket id right?

2016-09-27 19:40 UTC, sevein commented
Remember to name the branch and the pull request title after the public Redmine ticket next time pleaseeee

2016-09-27 21:29 UTC, mcantelon commented on apps/qubit/modules/settings/actions/securityAction.class.php
> +    $googleMapsApiKey = QubitSetting::getByName('google_maps_api_key');
Hrm... maybe we can put it into global until there are other API keys to group with it.

2016-09-27 21:29 UTC, mcantelon commented on plugins/sfIsdiahPlugin/modules/sfIsdiahPlugin/templates/indexSuccess.php
> +  <div id="front-map" class="simple-map" data-key="<?php echo $keyProperty->value ?>" data-latitude="<?php echo $latitude ?>" data-longitude="<?php echo $longitude ?>"></div>
Sounds good.

2016-09-27 21:33 UTC, sevein commented on apps/qubit/modules/settings/actions/securityAction.class.php
> +    $googleMapsApiKey = QubitSetting::getByName('google_maps_api_key');
Makes sense!

2016-09-27 21:58 UTC, mcantelon commented
Oops... PR and commits reference public ticket, but I forgot to rename the branch. Sorry. :(

2016-09-28 23:32 UTC, mcantelon commented
OK, ready for another review.

2016-09-28 23:45 UTC, sevein commented
Can we merge the translations? Their classes also have the same names?

2016-09-29 18:04 UTC, mcantelon commented
I've never dealt with translations so not sure what you mean.

2016-09-29 18:05 UTC, sevein commented
Sorry, I meant the database migrations.

2016-09-29 18:11 UTC, sevein commented
`arMigration0146.class.php` => `class arMigration0146`
`arMigration0147.class.php` => `class arMigration0146`

In any case, I understand that a migration is necessary for `digital_object_geolocation` because we want it to be enabled by default. Do we need a migration for `google_maps_api_key` knowing that the default is not to have a key?

2016-09-29 18:15 UTC, mcantelon commented
Oops... sorry I'll fix that.

2016-09-29 18:16 UTC, mcantelon commented
OK, fixed!

2016-09-29 18:27 UTC, sevein requested changes
I'm still hoping that we can save that extra migration, can we? Me 15 mins ago:

> In any case, I understand that a migration is necessary for digital_object_geolocation because we want it to be enabled by default. However, do we need a migration for google_maps_api_key knowing that the default is to not have a key?

2016-09-29 18:27 UTC, sevein commented on lib/task/migrate/migrations/arMigration0146.class.php
> +}
Do we need this migration?

2016-09-29 18:27 UTC, sevein commented on data/fixtures/settings.yml
> +    value:
Do we need this?

2016-09-29 18:27 UTC, sevein commented on apps/qubit/modules/settings/actions/globalAction.class.php
> +      $setting = QubitSetting::getByName('google_maps_api_key');
We can save the migration for `google_maps_api_key` if you create the object on demand, right here, if `$setting` is `NULL`. You did something very similar int he following commit a while ago: f3041d0d291437d5a0816f8c3488b36661e5f1f2.

2016-09-29 18:36 UTC, mcantelon commented on apps/qubit/modules/settings/actions/globalAction.class.php
> +      $setting = QubitSetting::getByName('google_maps_api_key');
Cool... okay I'll implement that.

2016-09-29 18:59 UTC, mcantelon commented on apps/qubit/modules/settings/actions/globalAction.class.php
> +      $setting = QubitSetting::getByName('google_maps_api_key');
Okay, I've gotten rid of the Google Maps API key migration.

2016-09-29 19:03 UTC, sevein approved these changes

2016-09-29 19:09 UTC, sevein commented
Squash, please!

2016-09-29 19:11 UTC, mcantelon commented
Merged.

2016-09-29 19:11 UTC, closed without merging