Description updates/index functions, refs #10458
artefactual/atom pull request #454
Opened 2016-11-02 21:57 UTC by mcantelon

* Added ElasticSearch indexing of functions
* Changed description updates page to use ElasticSearch
* Redesigned description updates page

2016-11-02 22:03 UTC, mcantelon commented
Note: the `_updatesSearch.php` template generates the radio button HTML manually to output it in a non-standard way so it looks like the analyst's mockup for it.

2016-11-03 18:12 UTC, sevein requested changes
It works. I'm including many comments in my review but some of them suggest changes that are probably not realistic considering how much time you have left and that's ok, we can address later but it's good to keep them in mind or discuss if you want.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +      $this->nameColumnDisplay = ($this->className == 'QubitInformationObject') ? 'Title' : 'Name';
Not using i18n.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/_updatesSearch.php
> +              <?php foreach($form->getWidgetSchema()->dateOf->getChoices() as $value => $translatedText): ?>
`foreach` is a statement not a func

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/descriptionUpdatesSuccess.php
> +  <?php echo get_partial('search/updatesSearch', array(
Can you change the style of this component so it doesn't float on top of the `.table`? To make it visually more attractive I think we need to create some room between the search widget and the table.

This is what I am seeing now:

![screenshot](http://i.imgur.com/fuPjZXz.png)

I would expect something like:

![screenshot](http://i.imgur.com/q2Cm1XS.png)

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
>      $this->form->bind($request->getRequestParameters() + $request->getGetParameters() + $defaults);
It's unclear to me that we need to use getRequestParameters in this context bound to the form, do we?

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +    return $resultSet;
Do you need to return the `$resultSet`? It doesn't seem that you're making use of it and it's carred to the template via the pager, right?

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +    switch ($this->form->getValue('dateOf'))
Regarding to separation of roles, should this function receive the value of `dateOf` as a parameter instead of looking up the form?

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +  private function addDateRangeQuery(&$queryBool)
I believe that objects are always passed by reference in PHP5 and you don't need to use the `&` operator.

> In PHP 5 there is a new Object Model. PHP's handling of objects has been completely rewritten, allowing for better performance and more features. In previous versions of PHP, objects were handled like primitive types (for instance integers and strings). The drawback of this method was that semantically the whole object was copied when a variable was assigned, or passed as a parameter to a method. In the new approach, objects are referenced by handle, and not by value (one can think of a handle as an object's identifier).

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +  private function addDateRangeQueryClause(&$queryBool, $field)
Same here, objects are always passed by reference.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +    if (null !== $this->form->getValue('startDate'))
Same here, receive parameter instead of form lookup?

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
> +    if (null !== $this->form->getValue('endDate'))
Same here, receive parameter instead of form lookup?

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/_updatesSearch.php
> +<section class="advanced-search-section">
This is just a general thought about _updatesSearch.php. Why do you implent it as its own partial? Is it for future composability of reusability? Do you think there will be a case for it?

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/_updatesSearch.php
> +                  <input type="radio" name="dateOf" value="<?php echo $value ?>" <?php echo $form->getValue('dateOf') == $value ? 'checked' : '' ?>>
I've read your note about why you're using raw HTML here but wouldn't be more correct to implement our own widget form like `arWidgetFormSelectRadio` to avoid having too much logic in our templates? I wouldn't do it if you're running out of time though.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/_updatesSearch.php
> +              <?php foreach($form->getWidgetSchema()->publicationStatus->getChoices() as $value => $translatedText): ?>
`foreach` is a statement.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/descriptionUpdatesSuccess.php
> +            <td>
Shouldn't this `<td></td>` be contained by the `if` clause? Otherwise we end up with an empty column / weird visual glitch when the user is search for `QubitFunction` or `QubitTerm`.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/descriptionUpdatesSuccess.php
> +          <tr class="<?php echo 0 == @++$row % 2 ? 'even' : 'odd' ?>">
I would recomend to use `table-striped` instead. We used it in `inventorySuccess.php` and I think it worked nicely IIRC.

2016-11-03 18:12 UTC, sevein commented on apps/qubit/modules/search/templates/descriptionUpdatesSuccess.php
> +          <?php $doc = $result->getSource() ?>
We tend to use `getData()` instead of `getSource()` (see `\Elastic\Result`) just in case we want to access outter fields of the document and not just the stuff in `_source`. Some of the helpers you're using later may be expecting them to be available down the road.

2016-11-03 18:12 UTC, sevein commented on js/dominion.js
> +      var $advancedSearch = $('body.informationobject.browse').add('body.search.descriptionUpdates');
I think that a comma-separated list of selectors will be faster because only one jQuery object is built. The docs of add() give more details.

2016-11-03 18:12 UTC, sevein commented on plugins/arElasticSearchPlugin/lib/model/arElasticSearchFunction.class.php
> +    $actors = QubitPdo::fetchAll($sql, array('QubitFunction'));
I've never realized we use fetchAll here (in similar classes for other entities). The only reason why we do it seems to be that `count()`. It sounds like we should use SQL instead for that count and then make another query using just `fetch` so we can use a scrollable cursor in the loop to save memory right? It doesn't have to happen now though unless you have time :)

2016-11-03 19:11 UTC, mcantelon commented on apps/qubit/modules/search/actions/descriptionUpdatesAction.class.php
>      $this->form->bind($request->getRequestParameters() + $request->getGetParameters() + $defaults);
Good question... I'll see if it works without it.

2016-11-03 19:13 UTC, mcantelon commented on apps/qubit/modules/search/templates/_updatesSearch.php
> +<section class="advanced-search-section">
Just to make the parent template less cluttered. I could put it in there too.

2016-11-03 19:16 UTC, mcantelon commented on js/dominion.js
> +      var $advancedSearch = $('body.informationobject.browse').add('body.search.descriptionUpdates');
I tried using the command-separated initially and for some reason couldn't get it to work. But I'll do a quick re-try.

2016-11-09 19:19 UTC, mcantelon commented
OK, I've updated, addressing all feedback I think (except for removing fetchAll and creating a arWidgetFormSelectRadio variant).

2016-11-09 23:28 UTC, sevein commented
Thank you, looks great! :+1:

2016-11-09 23:28 UTC, sevein approved these changes

2016-11-10 21:35 UTC, mcantelon commented
Thanks! Merged.

2016-11-10 21:35 UTC, closed without merging