Enable ACL checks on export, Refs #10000
artefactual/atom pull request #463
Opened 2016-11-14 18:04 UTC by sbreker

Historically, ACL checks are disabled for CLI tasks. This applied also to
asynchronous background jobs. CSV and XML export background jobs launched
from the Clipboard required ACL checks to be run. This change allows a
background job to conditionally enable ACL checks.

arBaseJob has two new methods that activate ACL checks when called. This is
optional for each background job so as not to impact existing functionality.
Currently, the only two background jobs that call these methods to activate
ACL checks are arInformationObjectExportJob and arXmlExportJob.

2016-11-14 20:19 UTC, sevein commented
If the `cli` environment is going to be different from the context of workers, I wonder if we should create a custom `worker` environment. Making the distinction between these two at that level of abstraction may provide us with better way to control behavior in our application, without having to pass extra arguments around, change signatures, etc...

Here is where we decide which environment a particular task is going to use: https://github.com/artefactual/atom/blob/qa/2.4.x/lib/task/jobs/clearJobsTask.class.php#L44. We could add custom settings for a new `worker` environment here: https://github.com/artefactual/atom/blob/qa/2.4.x/apps/qubit/config/settings.yml.tmpl even though I think we could just start with the same settings that `cli` has. In [factories.yml](https://github.com/artefactual/atom/blob/qa/2.4.x/config/factories.yml) we could also pass a new parameter to one of the factories (e.g. `user`) if that was necessary, for example, to bootstrap `myUser` with a new parameter specific to the `worker` environment.

I'm not sure if it's the right approach though. I'm curious to hear thoughts from @mcantelon @MikeFE @jraddaoui.

2016-11-14 20:24 UTC, sbreker commented
Ultimately, I was trying to come up with a solution that could be triggered on a case by case basis to avoid triggering ACL checks for all background jobs as I didn't know what the fallout of that would be.

2016-11-15 22:17 UTC, jraddaoui commented
@sevein's solution sounds great, if I'm understanding well, we only need to duplicate the current env. for 'cli' calling it 'worker' and use it in the jobWorkerTask, and with that you won't need to pass the backgroundJob option all around.

But we are still going to need to do the log in to share the user in the jobs, right? Maybe that's something that can be done without passing the user id as a param and using the related QubitJob userId instead.

2016-11-16 19:02 UTC, MikeFE commented on lib/job/arBaseJob.class.php
> +  protected function isBackgroundJob(&$parameters)
can we change the function name here since it's a setter? The function name makes me think it's some sort of checker function that returns a bool

2016-11-16 19:05 UTC, sevein commented on lib/job/arBaseJob.class.php
> +  protected function isBackgroundJob(&$parameters)
I agree but I think that method is going to be gone very soon. He's giving a try to that `worker` environment instead.

2016-11-16 19:23 UTC, MikeFE commented on lib/job/arBaseJob.class.php
> +  protected function isBackgroundJob(&$parameters)
yeah I spoke with Steve and it sounds like this is changing anyway. Didn't know, sorry!

2016-11-17 14:25 UTC, sevein commented on lib/model/QubitInformationObject.php
> +        $addCondition = QubitAcl::check($child, 'read', $options);
What exactly is in `$options` that you need to pass to `QubitAcl`? `levels`? `public`?

2016-11-17 14:54 UTC, sevein commented
I've added a couple of comments but 👍 !
I'm glad that this is working out but the issue proves that running long-running workers off our codebase is definitely not what we built this for originally and there are big chances that we'll need to keep patching things to fix new bugs unless we implement new workers differently. Nothing stop us to implement the next worker ability in a different platform, language, framework, etc...

2016-11-17 14:55 UTC, sevein requested changes
I've added a couple of comments but 👍 !
I'm glad that this is working out but the issue proves that running long-running workers off our codebase is definitely not what we built this for originally and there are big chances that we'll need to keep patching things to fix new bugs. Nothing stop us to implement the next worker ability in a different platform, language, framework, etc...

2016-11-17 14:55 UTC, sevein commented on plugins/qbAclPlugin/lib/QubitAcl.class.php
> +  public static function destruct()
This method could use some docs to describe our very particular use case, perhaps something like:

```
Each request is completely unique in PHP however our workers run in a loop
where state is held across jobs. This class was built as a singleton so we
need this extra method to void the instance when needed.
```

2016-11-17 17:11 UTC, sbreker commented on lib/model/QubitInformationObject.php
> +        $addCondition = QubitAcl::check($child, 'read', $options);
No longer necessary.  Missed removing it when I was revising the work.

2016-11-17 17:11 UTC, sbreker commented on plugins/qbAclPlugin/lib/QubitAcl.class.php
> +  public static function destruct()
I added a comment at the call but missed adding one here.  Good idea.

2016-11-17 17:19 UTC, sbreker commented on lib/model/QubitInformationObject.php
>          $addCondition = QubitAcl::check($child, 'read');
Removed $options array.

2016-11-17 17:30 UTC, sevein approved these changes

2016-11-17 20:27 UTC, MikeFE commented on lib/job/arBaseJob.class.php
> +   * @param int none
int none? :P

2016-11-18 18:11 UTC, sbreker commented on lib/job/arBaseJob.class.php
> +   * @param int none
I've removed this.  😄

2016-11-18 18:17 UTC, closed without merging