Add support for other entities on the clipboard
artefactual/atom pull request #515
Opened 2017-02-10 22:45 UTC by MikeFE

Add clipboard/export support to repos and actors

This new feature adds 'add to clipboard' buttons for both repositories and
actors. The clipboard now has an additional drop down box to allow the user to
change the clipboard view between the three entity types (archival descs,
repositories and actors), to clear the clipboard for each entity type, and to
export each entity type.

Asynchronous jobs to export actors (both CSV and EAC XML), and repositories
(CSV) were also added. Additionally, the export repository task that was
in its own branch was integrated into this work.

sortPicker has been generalized into genericPicker where you can specify the
drop down label and options. You can still call sortPicker as it just invokes
genericPicker with sort-specific labels hard coded.

To summarize:

- Archival descriptions, actors and repositories can now all be added to
  clipboard

- Asynchronous jobs to export all these three entity types are in place

- You can switch between entity types in the clipboard via a dropdown menu

- You can clear the clipboard of each entity type depending on the currently
  selected type.

- Made a more generic sortPicker, "genericPicker."

2017-02-16 18:09 UTC, jraddaoui commented
Wow, this is quite a pull request @MikeFE!

I guess it will be too much work to split it in various PR at this point, but I think we should. Or, if we don't have time to do that, at least we should improve a lot the description (and the commit message that will be used in the squashed merge) as it doesn't even talk about the asynchronous jobs.

For the next time we work in big features, I'd love to advice that we start the code review process earlier, that way we could have spotted this sooner, reviewed the clipboard part and merged it, to avoid conflicts in the subsequent PRs, etc. Also, I'd appreciate clearer individual commit messages and better descriptions.

About the code, it looks great overall! But I'll take a deeper look tomorrow or on Monday, just in case we can split the PR or improve the description.

2017-02-16 18:44 UTC, MikeFE commented
Sounds good Radda. Yeah, this PR got way larger than originally anticipated since this feature went way over hours and we vastly under estimated how much work we were going to do on it unfortunately, but I'm totally open to discussion on how we can avoid this sort of thing in the future.

regards

2017-02-20 17:11 UTC, jraddaoui commented
Great @MikeFE! Please, could you improve the description then? Thanks!

2017-02-21 21:30 UTC, MikeFE commented
OK I rewrote the PR description and gave it my best shot. Hopefully that's what you were looking for :)

2017-02-22 12:10 UTC, jraddaoui requested changes
Hi @MikeFE,

Thank you for the description update, we should use it as the commit body when we merge this work. I'd add a small note about the generic picker changes in there too.

I've added a few comments, some that I think must be addressed before merging and others not so important. I also have the feeling that we could have covered all export cases with only one export job, as there is a lot of duplicated code in those classes, but it may be too late to change it now.

Great work!

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/default/templates/_genericPicker.php
> +
We don't use to start a template with an empty line

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/default/templates/_sortPicker.php
> +                       'param' => 'sort', 'label' => __('Sort by'))) ?>
But we use to add a new line at the end of all files. Check: http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

If you use Sublime Text, that can be set in a config setting, so it automatically adds a new line at the end if it's not there when saving.

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/object/actions/exportAction.class.php
> +      'objectType' => $request->getParameter('objectType'),
You could use `$this->objectType` in here as it was obtained before with a default value

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/repository/templates/_browseCardView.php
> +        <p><?php echo get_component('object', 'clipboardButton', array('slug' => $doc['slug'], 'wide' => true)) ?><?php echo $authorizedFormOfName ?></p>
I think we should use the small clipboard button and place it in the right side as it takes a lot of place in those cards footer. You may need to fix the text ellipsis or place the button in another container.

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/repository/templates/_browseTableView.php
> +        <?php echo get_component('object', 'clipboardButton', array('slug' => $doc['slug'], 'wide' => true)) ?>
Same here, it doesn't look right alongside the auth. form of name as it changes the button position. I'd use the small button in a new column at the end of the table, without column header title, so it takes only the button width. We probably don't have time to add the column toggle (All/None) in the column header, like in the description updates page, but we should check it, just in case it's an easy change.

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/user/actions/clipboardAction.class.php
> +    $this->entityType = 'Qubit'.ucfirst($request->getGetParameter('type', 'informationObject'));
This variable could be created after `$this->type` is set, to avoid getting the parameter from the request twice.

2017-02-22 12:10 UTC, jraddaoui commented on apps/qubit/modules/user/actions/clipboardClearAction.class.php
>      if (count($slugs) == 0)
We probably need to check `$slugs[$this->type]` in here, like the changes in `clipboardAction.class.php`

2017-02-22 12:10 UTC, jraddaoui commented on lib/flatfile/config/QubitActor-atom.yml
> +  - maintenanceNotes
New line at the end.

2017-02-22 12:10 UTC, jraddaoui commented on lib/flatfile/config/QubitActor.yml
> +cacheTaxonomies:
;) the same, new line

2017-02-22 12:10 UTC, jraddaoui commented on lib/task/migrate/migrations/arMigration0137.class.php
> +        $menu->label = 'Clear all selections';
I think this is a 2.3 migration, so instances upgraded from 2.3 to 2.4 won't get the label change. I think we must create a new migration script.

2017-02-22 12:10 UTC, jraddaoui commented on plugins/sfIsaarPlugin/modules/sfIsaarPlugin/templates/indexSuccess.php
> +        </li>
I think this is missing in the repository index page.

2017-02-22 19:23 UTC, MikeFE commented on apps/qubit/modules/default/templates/_sortPicker.php
> +                       'param' => 'sort', 'label' => __('Sort by'))) ?>
hmm OK I use VSCode and didn't notice it wasn't adding the newlines! I'll look into it :)

2017-03-03 17:07 UTC, jraddaoui commented on plugins/arDominionPlugin/css/less/buttons.less
> +button.clipboard.clipboard-repository-browse {
You could have place this inside the `button.clipboard` section bellow using `&.clipboard-repository-browse`. The transformation to CSS will be the same but it makes a nicer LESS with the nested rules.

2017-03-03 17:08 UTC, jraddaoui commented on lib/task/migrate/migrations/arMigration0150.class.php
> +      $menuItem->label = 'Clear all selections';
Could you remove the changes in lib/task/migrate/migrations/arMigration0137.class.php, please.

2017-03-03 17:17 UTC, sevein commented on lib/task/migrate/migrations/arMigration0150.class.php
> +      $menuItem->label = 'Clear all selections';
I think we shouldn't change previous migrations, right? We should only update state from newer migrations.

2017-03-03 17:17 UTC, sevein commented on lib/task/migrate/migrations/arMigration0150.class.php
> +      $menuItem->label = 'Clear all selections';
@MikeFE I think you should replace `$menuItem->label = 'Clear all selections';` with:

```php
$menuItem->setLabel('Clear all selections', array('culture' => 'en'));
```

2017-03-03 17:18 UTC, sevein commented on lib/task/migrate/migrations/arMigration0150.class.php
> +      $menuItem->sourceCulture = 'en';
This one you don't need it because it should already have that value in it.

2017-03-03 17:32 UTC, jraddaoui commented
Hi @MikeFE, looking great!

Now that we have the button in both repository view options I think we should add it to the card (digital object) view in the IO browse page, it should be an easy addition. Also, for those card views, since we are placing the clipboard button to the right in all cases, I'd place it in the right bottom corner of the card instead of at the left-bottom corner.

And please, add a little note about the generic picker in the description. Thanks!

2017-03-03 17:52 UTC, jraddaoui commented
For following PRs, could you avoid to force push until just before the merge. It's not a big deal but it keeps the commit history and review messages in place ;)

2017-03-08 16:17 UTC, jraddaoui commented
Hi @MikeFE,

After all, for the clipboard button inside the cards (DO browse and repository browse in card view) we could have avoided passing the parameter and adding the class by adding the CSS rules for `.masonry-brick button.clipboard`, it will remove some code but feel free to leave it be. But please, remove the unneeded changes in lib/task/migrate/migrations/arMigration0137.class.php.

Thanks!

2017-03-08 16:17 UTC, jraddaoui approved these changes

2017-03-08 19:42 UTC, MikeFE commented
merged into qa/2.4.x 4403962532fb87df6623c335a7fc66f5fbd8b214

2017-03-08 19:42 UTC, closed without merging

2017-03-09 09:16 UTC, jraddaoui commented
Hi @MikeFE, 

Please, delete the development branches after merge. We're "starting" to have a big list of branches :)

Thanks!!

2017-03-09 09:20 UTC, jraddaoui commented
Also, the commit message used in the merge doesn't have a reference to the Redmine ticket ...