Dev/issue 10047 rest return json
artefactual/atom pull request #526
Opened 2017-02-23 20:05 UTC by mcantelon

* Added catch-all /api route to generate endpoint not found exception
* Added filter to handle API exceptions and return all errors (except sfStopException) as JSON
* Fixed class naming inconsistencies
* Made all REST API exception instances specify an error message

2017-02-26 16:40 UTC, sevein requested changes
Looking good. I have one suggestion but it's not critical. If you define a
new intermediate class `QubitApiException` and establish the following
hierarchy:

```
QubitApiException
 ├── QubitNotFoundException
 ├── QubitApiNotAuthorizedException
 ├── QubitApiForbiddenException
 └── QubitApiBadRequestException
```

You could add some more context to the exception (status code, etc...) and use
that to simplify the implementation of the `arRestApiPluginFilter` filter,
e.g.: (quick draft, have not tested)

```php
class arRestApiPluginFilter extends sfFilter
{
  public function execute($filterChain)
  {
    sfConfig::set('sf_web_debug', false);
    try
    {
      $filterChain->execute();
    }
    catch (sfStopException $e)
    {
      // Ignore stop exceptions
      return;
    }
    catch (Exception $e)
    {
      $this->setErrorResponse($e);
    }
  }

  private function setErrorResponse(Exception $error)
  {
    $response = sfContext::getInstance()->response;
    $response->setHttpHeader('Content-Type', 'application/json; charset=utf-8'

    // Defaults for unknown API exception.
    $statusCode = 500;
    $errorMsg = 'Internal error';
    $errorId = 'internal-error';

    if (is_subclass_of($error, 'QubitApiException'))
    {
      $statusCode = $error->getStatusCode();
      $errorMsg = $error->getMessage();
      $errorId = $error->getId();
    }

    // Translate exception into response data
    $payload = arRestApiPluginUtils::arrayToJson(array('id' => $errorId, 'message' => $errorMsg));

    $response->setContent($payload);
  }
}
```

You could even define a new `QubitApiUnknownException` that wraps the unknown exception and have the signature of `setErrorResponse` only receive QubitApiException instances (type hinting). That way you wouldn't even need to call `is_subclass_of` and have the defaults for the unknown error in `QubitApiUnknownException` like the others (`500`, `Internal error`, etc...).

2017-02-26 16:40 UTC, sevein commented on plugins/arRestApiPlugin/lib/arRestApiPluginFilter.class.php
> +    sfConfig::set('sf_web_debug', false);
Can you remember why we're doing this?

I'm sure it's still relevant and this is probably a good place, but it'd be nice to add a comment if you remember.

2017-02-26 16:40 UTC, sevein commented on plugins/arRestApiPlugin/modules/api/actions/informationobjectsUpdateAction.class.php
> +      throw new QubitApiForbiddenException('Forbidden');
It'd be nice to have a default exception message so we don't have to give it one. If you changed `QubitApiForbiddenException` as the following:

```php
class QubitApiForbiddenException extends Exception
{
  const MESSAGE = 'Forbidden';

  const STATUS_CODE = 403;

  public function __construct($message = null, $code = 0, Exception $previous = null)
  {
    $message = is_null($message) ? self::MESSAGE : $message;

    return parent::__construct($message, $code, $previous);
  }

  public function getStatusCode()
  {
    return self::STATUS_CODE;
  }
}
```

Then `throw new QubitApiForbiddenException;` would be enough but we could still add a custom message when necessary. Does that sound like a good idea?

2017-02-26 16:40 UTC, sevein commented on plugins/arRestApiPlugin/lib/exception/QubitApi404Exception.class.php
> +class QubitApi404Exception extends Exception
Should we rename to `QubitApiNotFoundException` to be consistent with the other classes where the status code is never included?

2017-02-26 21:56 UTC, mcantelon commented on plugins/arRestApiPlugin/lib/arRestApiPluginFilter.class.php
> +    sfConfig::set('sf_web_debug', false);
Hrm... good question. I'll see what happens when I take it out (maybe in dev mode filters inject some debugging-related content?).

2017-02-26 21:57 UTC, mcantelon commented on plugins/arRestApiPlugin/modules/api/actions/informationobjectsUpdateAction.class.php
> +      throw new QubitApiForbiddenException('Forbidden');
Good idea!

2017-02-27 20:40 UTC, sevein commented on plugins/arRestApiPlugin/modules/api/actions/informationobjectsUpdateAction.class.php
> +      throw new QubitApiForbiddenException('Forbidden');
I think this is a better approach :smile: 
https://github.com/symfony/http-kernel/tree/master/Exception

2017-02-28 16:55 UTC, sevein commented on plugins/arRestApiPlugin/lib/arRestApiPluginFilter.class.php
> +    sfConfig::set('sf_web_debug', false);
Right, I think it's safer if we leave it! Thanks for taking a look.

2017-02-28 16:55 UTC, sevein approved these changes
👍

2017-02-28 19:21 UTC, mcantelon commented
Thanks!!! Merged.

2017-02-28 19:21 UTC, closed without merging