Added term usage CSV export task, refs #11058
artefactual/atom pull request #552
Opened 2017-04-13 21:59 UTC by mcantelon

Added a task to export, as CSV, terms, in a given taxonomy, that have been
assocated with information objects.

2017-04-17 19:07 UTC, jraddaoui requested changes
Looks great Mike! Just a few notes.

2017-04-17 19:07 UTC, jraddaoui commented on lib/flatfile/config/QubitTerm.yml
> +  - culture
Do we really need this file?

2017-04-17 19:07 UTC, jraddaoui commented on lib/task/export/csvExportTermUsageTask.class.php
> +    else if(isset($options['taxonomy-name']))
We normally use elseif and it's missing the space after the if.

2017-04-17 19:07 UTC, jraddaoui commented on lib/task/export/csvExportTermUsageTask.class.php
> +    */
Could you remove the empty lines at the beginning and end and add one after the comment block? And I prefer the full block ...

/*
 *
 *
 */

2017-04-17 19:07 UTC, jraddaoui commented on lib/task/export/csvExportTermUsageTask.class.php
> +    $format = 'SELECT DISTINCT t.id FROM %s t INNER JOIN %s r ON r.term_id=t.id WHERE t.taxonomy_id=? ORDER BY t.id';
I think we should add another JOIN in this query with the object table, and check the class_name column to find only relations with QubitInformationObject.

2017-04-17 19:11 UTC, jraddaoui commented
It looks like the commit message refers to a client ticket, could you create a public one explaining the task, etc. And I'm not sure if @fiver-watson would like to add some docs about it.

2017-04-19 20:42 UTC, mcantelon commented
Updated and ready for another review... thanks!

2017-04-19 21:11 UTC, mcantelon commented
(Oops, didn't mean to close PR.)

2017-04-19 21:25 UTC, MikeFE commented
LGTM :+1: -- don't forget to make the merge commit msg point to a public ticket when merging into mainline AtoM (can use Redmine's duplicate ticket functionality if one doesn't exist).

2017-04-19 21:50 UTC, mcantelon commented
Thanks Mike!

2017-04-19 22:55 UTC, merged