Create actor unlinker CLI task, Refs# 11753
artefactual/atom pull request #651
Opened 2018-01-17 21:28 UTC by sbreker

CLI task that will update cases where a creator could be linked to
information object using inheritance.

If a descr slug is specified, all creators on this node + descendants
will be examined.

If an actor slug is specified, all descrs with this creator will be
examined.
- only this actor can be modified.
- in cases where more than one creator would have been unlinked, nothing
will be done.

If actor or descr is NOT specified, all nodes will be examined to see
if creators could be inherited instead.

- corrected short description inpromoteUserToAdminTask.class.php

2018-01-26 06:49 UTC, mcantelon commented
A couple of minor nitpicks, but otherwise looks good!

2018-01-26 16:25 UTC, mcantelon requested changes

2018-01-26 16:25 UTC, mcantelon commented on lib/task/tools/unlinkCreatorTask.class.php
> +        if (null == $event->getPlace()->name && null == $event->date && null == $event->name && null == $event->description && null == $event->startDate && null == $event->endDate && null == $event->
Making this multi-line might be good for code readability.

2018-01-26 16:25 UTC, mcantelon commented on lib/task/tools/unlinkCreatorTask.class.php
> +  private function unlinkCreators($options = array())
This function's pretty long so could be could to break some logic out into other class methods.

2018-01-26 16:25 UTC, mcantelon commented on lib/task/tools/unlinkCreatorTask.class.php
> +Unlink creators from descriptions so creator inheritance can be used.
Could be good to expand on the functionality in more detail here.

2018-01-26 19:08 UTC, mcantelon approved these changes

2018-01-26 19:08 UTC, mcantelon commented
👍

2018-01-26 21:35 UTC, closed without merging

2018-02-01 19:20 UTC, MikeFE commented
In the future please don't forget to use arBaseTask, not sfBaseTask.