Permission-related fix to menu items, refs #11075
artefactual/atom pull request #673
Opened 2018-03-05 08:02 UTC by mcantelon

This fixes a permissions-related issue preventing the "Subjects" and
"Places" links from being displayed on the home page and in the "Browse"
menu.

The permission checking logic in the menu display relies on permissions from
security.yml files. The menu items meant to direct users to the index pages
for the place and subject taxonomies had paths that linked to the taxonomy
browse action instead which would then redirect to the taxonomy index action.
Because of restrictions on the taxonomy browse action this was causing the
menu items for places and subjects not to appear in menus for
non-authenticated users.

This is fixed by:

* Fixing an issue with the taxonomy module’s index action that prevented it
  from working correctly when called with an ID as a GET parameter
* Moving access control for the taxonomy module’s index action from
  security.yml to the action logic so place and subject can be accessible to all
* Changing the paths in the menu items for the place and subject taxonomies,
  using a data migration, to so the menu paths aren’t reliant on the taxonomy
  module browse action to redirect to the taxonomy module index action

This commit also removes some unnecessary logic from the taxonomy browse action.

2018-03-06 08:06 UTC, jraddaoui requested changes
Hi @mcantelon,

Looking great! Just a couple of suggestions and a comment about the genres taxonomy that may need feedback from @fiver-watson.

Thanks!

2018-03-06 08:06 UTC, jraddaoui commented on apps/qubit/modules/taxonomy/actions/browseAction.class.php
> +    $this->redirect(array('module' => 'taxonomy', 'action' => 'list'));
Nice. We could also remove the "browseSuccess" template after this.

2018-03-06 08:06 UTC, jraddaoui commented on apps/qubit/modules/taxonomy/actions/indexAction.class.php
> +    $unrestrictedTaxonomies = array(QubitTaxonomy::PLACE_ID, QubitTaxonomy::SUBJECT_ID);
I think @fiver-watson was asking for the genres taxonomy to be included in here too. We could also add a browse menu item for it now that we're adding a migration to modify them, if Dan likes the idea.

2018-03-06 08:06 UTC, jraddaoui commented on lib/task/migrate/migrations/arMigration0160.class.php
> + * Add new setting for permissive slug generation. DB column collation change.
Hehe, it always happens.

2018-03-06 08:06 UTC, jraddaoui commented on lib/task/migrate/migrations/arMigration0160.class.php
> +
We're caching the menus, which I believe is the reason of @fiver-watson not seeing the changes in the homepage. I'm not sure if this will be an issue in all the upgrades as it's using the "ViewCacheManager" and probably removing the ".cache" folder is enough. But, could you try to add something like what we use in the menu edit action to this migration? See:

https://github.com/artefactual/atom/blob/qa/2.5.x/apps/qubit/modules/menu/actions/editAction.class.php#L151-L156

2018-03-07 18:51 UTC, mcantelon commented on lib/task/migrate/migrations/arMigration0160.class.php
> + * Add new setting for permissive slug generation. DB column collation change.
LOL... good catch. ;D

2018-03-07 18:51 UTC, mcantelon commented on lib/task/migrate/migrations/arMigration0160.class.php
> +
Sounds good.

2018-03-13 22:54 UTC, mcantelon commented on lib/task/migrate/migrations/arMigration0160.class.php
> +
Running `sfContext::getInstance()->getViewCacheManager()` returns null so seems like there's no view cache manager available when running from CLI.

One thing we might want to do though, after running the migrate task, is clear *all* the caches which I think can be done with this code (which I think does the same thing as `php symfony cc`):

    $cacheClear = new sfCacheClearTask(sfContext::getInstance()->getEventDispatcher(), new sfFormatter());
    $cacheClear->run();

What do you think's the best way to go?

2018-03-14 12:30 UTC, jraddaoui commented on lib/task/migrate/migrations/arMigration0160.class.php
> +
I have vague recollection about `php symfony cc` not clearing the menus cache, that's why I asked. But you're right, if it's not as easy as using that piece of code, we can revisit later if it's needed.

Thanks for looking into this @mcantelon!

2018-03-14 12:30 UTC, jraddaoui approved these changes

2018-03-14 18:15 UTC, mcantelon commented on lib/task/migrate/migrations/arMigration0160.class.php
> +
Thanks!

2018-03-14 20:37 UTC, merged