Pass user to CSV import and sign in, refs #12083
artefactual/atom pull request #771
Opened 2018-08-09 03:58 UTC by mcantelon

Fixed issue where, when doing a CSV import from the web UI, via an asynchronous
job, information object audit logging wasn't noting the user that created the
job.

Added --user-id option to task for CSV import of information objects, and corresponding logic, to sign the user in before import.

Added, to QubitCsvImport, the relaying of the current logged-in user to to the import task as a CLI option (if information objects are being imported).

2018-08-09 08:04 UTC, jraddaoui requested changes
Thanks @mcantelon!

Code looks good, just a minor suggestion. The commit message looks a bit malformed though.

2018-08-09 08:04 UTC, jraddaoui commented on lib/task/import/csvImportTask.class.php
> +       if (null != $user = QubitUser::getOne($criteria))
Extra whitespace and, now that you're in there, I think you could use directly `getById`.

2018-08-09 18:28 UTC, mcantelon commented
Hi Radda. I think commit it okay, just not PR description.

Sorry, I forgot not to rebase this.

2018-08-10 08:57 UTC, jraddaoui approved these changes
Thanks @mcantelon!

2018-08-10 09:52 UTC, jraddaoui commented
@mcantelon, about the commit message body, what I saw was something like ...

```
Fixed issue where, when doing a CSV import from the web UI, via an
asynchronous
job, information object audit logging wasn't noting the user that
created the
job.

Added --user-id option to task for CSV import of information objects and
logic
to sign the user in before import.

Added, to QubitCsvImport, the relaying of the current logged-in user to
the import task as a CLI option (if information objects are being
imported).
```

This has happened to me before when using a commit editor, in my case it was on the Git panel of the Atom text editor, which adds an auto-jump to avoid passing the recommended 72 chars per line.

2018-08-10 12:39 UTC, mcantelon commented
Hi @jraddaoui ... hrm, weird.

Do you still see it for https://github.com/artefactual/atom/pull/771/commits/b1898278ee55b14b8cd1db17803cd850cbdc4624 ?

2018-08-10 15:45 UTC, jraddaoui commented
Hi @mcantelon, sorry no, in that last one they are okay, longer than 72, but that's not a big deal. ;)

2018-08-10 16:21 UTC, mcantelon commented
Awesome... thanks @jraddaoui!

2018-08-11 23:31 UTC, merged