Auth subject place access points, refs #12593
artefactual/atom pull request #809
Opened 2018-12-10 23:52 UTC by sbreker

This is Feature 1 of a larger project.

2018-12-11 02:26 UTC, mcantelon requested changes
Looks good! One one minor thing found and a question.

2018-12-11 02:26 UTC, mcantelon commented on lib/model/QubitActor.php
> +  public function getPlaceAccessPoints(/*array $options = array('events' => false)*/)
Ghost code. ;)

2018-12-11 02:26 UTC, mcantelon commented on lib/model/QubitObjectTermRelation.php
> +    $criteria->add(QubitTermI18n::NAME, $name);
Do we need to worry about culture?

2018-12-11 23:41 UTC, sbreker commented on lib/model/QubitActor.php
> +  public function getPlaceAccessPoints(/*array $options = array('events' => false)*/)
Removed this - see latest commit.

2018-12-11 23:42 UTC, sbreker commented on lib/model/QubitObjectTermRelation.php
> +    $criteria->add(QubitTermI18n::NAME, $name);
I think you're right.  I have added a new commit that adds 'culture' to $options and updates the calls accordingly.

2018-12-14 22:31 UTC, mcantelon commented
Looks good! Nice work! 👍

2018-12-14 23:11 UTC, mcantelon approved these changes

2018-12-18 19:33 UTC, closed without merging