Accessions save deletes relations, refs #12662
artefactual/atom pull request #815
Opened 2018-12-21 19:21 UTC by sbreker

All relations are being deleted and re-added every time a change to an
accession is saved regardless of which field is updated. This is causing
all related information objects to be reindexed when an accession is
saved - this can be quite slow if many descriptions are linked.

These lines should be comparing the relation "subjectId" and not
"objectId" - objectId contains the accession.id, subjectId contains the
info_obj.id.

2018-12-27 18:13 UTC, jraddaoui requested changes
Good catch @sbreker!

I think we don't save any data from related accessions in the ES index for IOs, so we could also set `indexOnSave` to false for [the new relations created after the check](https://github.com/artefactual/atom/blob/dff59ac7eebcd2eb9a62449b4697e17294ea7e2d/plugins/qtAccessionPlugin/modules/accession/actions/editAction.class.php#L330), to avoid a few more unnecessary request to ES.

2018-12-29 01:09 UTC, sbreker commented
Hi @jraddaoui!  As you suggested, I have made the additional change to prevent re-indexing information objects when relations are added to accessions - good idea!

2018-12-29 01:55 UTC, jraddaoui approved these changes
Thanks @sbreker!

2018-12-31 16:52 UTC, closed without merging

2018-12-31 17:58 UTC, jraddaoui commented
Merged in https://github.com/artefactual/atom/commit/44b295de2883b8821fc5597ac51e3a7ebc9a961d.