Initialize path as array instead of string
artefactual/atom pull request #903
Opened 2019-05-28 05:26 UTC by ross-spencer

This commit corrects the initialization of path in importBulkTask to an array
to counter breaking changes introduced in PHP 7.1 that prevented its previous
initialization to be silently converted to an array.

Connected to #902

2019-05-28 12:41 UTC, jraddaoui requested changes
Thanks @ross-spencer!

As mentioned in Slack, the change looks great, it's just missing the ref to a Redmine ticket.

2019-05-29 14:14 UTC, ross-spencer commented
:wave: @jraddaoui how does this look?

2019-05-29 14:41 UTC, fiver-watson commented
Hi @ross-spencer sorry to nitpick, but for fixes going in the public release, we prefer to reference publicly accessible tickets. I've made a copy of your internal ticket into the public project - see: 

* https://projects.artefactual.com/issues/13066

Any chance you could update the PR title to reference 13066 instead? Thanks!

2019-05-29 14:52 UTC, ross-spencer commented
:+1: @fiver-watson

2019-05-29 14:58 UTC, fiver-watson commented
Thanks!

2019-05-29 16:30 UTC, jraddaoui approved these changes
Thanks @ross-spencer!

2019-05-29 17:56 UTC, closed without merging