Update storage perms, refs #13169
artefactual/atom pull request #966
Opened 2019-09-10 17:29 UTC by fiver-watson

In the 2.4 release, we discovered some inconsistencies in the default permissions, and that authenticated users who were not part of any group could access modules they should not be able to view. We corrected many of these in issue #[11075](https://projects.artefactual.com/issues/11075).

However, in that fix, we implemented too extreme a solution, allowing only administrators to view the physical storage module. There are many cases where Editors may need access, and local translators may also need to add translated container names.

It turns out that the default permissions are contained in a configurable YAML file, located here:

* https://github.com/artefactual/atom/blob/HEAD/apps/qubit/modules/physicalobject/config/security.yml

This fix will change the default permissions so that:

* Administrators, Contributors, Editors, and Translators can view and browse physical storage
* Administrators, Editors, and Translators, can edit physical storage containers
* Administrators and Editors can delete physical storage containers

For any users who wish to restrict these permissions further, they can make local edits to the YAML file listed above.

2019-09-10 17:38 UTC, djjuhasz requested changes

2019-09-10 17:38 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +  is_secure: true
It's not necessary to specify `is_secure: true` for each action, it's sufficient that it's specified for the "all:" permissions block.  I would also move the "all:" block to the top of the security list, just for legibility but it's not necessary.

2019-09-10 17:39 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +  is_secure: true
Ref: https://symfony.com/legacy/doc/reference/1_4/en/08-Security

2019-09-10 23:37 UTC, djjuhasz requested changes
As a contributor I can create a new physical storage location via "Archival description > Link physical storage" and "Create new container" (uses physicalobject/autocomplete permission).  After creating the physical object I see a link to it from the archival description view page, but when I click the link I get a "permission denied" page:

![physical_storage_acl_contributor](https://user-images.githubusercontent.com/626135/64657599-14201b80-d3e9-11e9-9820-eaae7e2a522e.png)

I think we should grant at least "index" (view) permissions to the contributor to allow viewing existing physical objects.

ALSO, as a contributor I see the "Manage > Physical storage" menu, but if I click the menu item I get a permission denied page.  I think we should either allow contributors to browse physical storage, or hide the menu item from them.

2019-09-10 23:37 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +   credentials: [[administrator, editor, translator ]]
Missing a space before "administrator".

2019-09-10 23:37 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +   credentials: [[administrator, editor, translator ]]
Missing a space before "administrator".

2019-09-10 23:37 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +   credentials: [[ administrator, editor, translator ]]
Indent should be 2 spaces only.  Three spaces is used here and for every subsequent "credentials" line.

2019-09-10 23:47 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +autocomplete:
Trailing whitespace

2019-09-10 23:47 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +delete:
Trailing whitespace

2019-09-10 23:48 UTC, djjuhasz commented on apps/qubit/modules/physicalobject/config/security.yml
> +edit:
Trailing whitespace

2019-09-11 14:30 UTC, fiver-watson commented
Hi! Ok, the ability for contribs to link or add locations via the descriptions, but not browse the module, was intentional, but I'm open to allowing them browse permissions. I'm not sure what permission controls whether or not the option appears in the Manage menu in any case. I'll give it another go.

2019-09-11 18:08 UTC, djjuhasz approved these changes
Looks good!

2019-09-11 18:19 UTC, fiver-watson commented
Merged into qa/2.6.x in https://github.com/artefactual/atom/commit/378a77feb80ea9040ad4057fe1388dc6d552a7b3

2019-09-11 18:19 UTC, closed without merging